a=int(input('Enter a '))
b=int(input('Enter b '))
c=int(input('Enter c '))
p=int(input('Enter p '))
q=int(input('Enter q '))
r=int(input('Enter r '))
x=(b*r-q*c)/(a*q-p*b)
y=(p*c-a*r)/(a*q-p*b)
print('(',x,',',y,')')